# Generated by Django 6.0 on 2025-12-29 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='TOSS_PAYMENTS', max_length=30)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('order_id', models.CharField(help_text='주문 ID', max_length=80)),
                ('payment_key', models.CharField(blank=True, help_text='토스 PaymentKey', max_length=120, null=True)),
                ('fail_code', models.CharField(blank=True, max_length=80, null=True)),
                ('fail_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='예약 ID', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('SUBWAY', 'Subway')], default='FLIGHT', max_length=10)),
                ('status', models.CharField(choices=[('CONFIRMED_TEST', 'Confirmed (Test)'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('title', models.CharField(help_text='예약 제목 (예: GMP -> CJU)', max_length=200)),
                ('start_at', models.DateTimeField(help_text='여행 시작 일시')),
                ('end_at', models.DateTimeField(blank=True, help_text='여행 종료 일시', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='총 결제 금액', max_digits=12)),
                ('currency', models.CharField(default='KRW', help_text='통화', max_length=3)),
                ('provider', models.CharField(blank=True, help_text='항공 데이터 제공사', max_length=50, null=True)),
                ('provider_ref', models.CharField(blank=True, help_text='제공사 Flight/Offer ID', max_length=120, null=True)),
                ('test_order_no', models.CharField(help_text='UI 노출용 테스트 주문번호', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationFlightSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10)),
                ('segment_no', models.IntegerField(help_text='구간 순서')),
                ('airline_code', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dep_airport', models.CharField(help_text='출발 공항 코드', max_length=10)),
                ('arr_airport', models.CharField(help_text='도착 공항 코드', max_length=10)),
                ('dep_at', models.DateTimeField(help_text='출발 시각')),
                ('arr_at', models.DateTimeField(help_text='도착 시각')),
                ('duration_min', models.IntegerField(blank=True, help_text='소요 시간(분)', null=True)),
                ('fare_per_person', models.DecimalField(blank=True, decimal_places=2, help_text='1인 기준 요금', max_digits=12, null=True)),
                ('seat_availability_note', models.CharField(blank=True, help_text='잔여 좌석 정보', max_length=80, null=True)),
            ],
            options={
                'db_table': 'reservation_flight_segments',
                'ordering': ['direction', 'segment_no'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_type', models.CharField(choices=[('ADT', 'Adult'), ('CHD', 'Child'), ('INF', 'Infant')], max_length=10)),
                ('full_name', models.CharField(help_text='승객 이름', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'reservation_passengers',
            },
        ),
        migrations.CreateModel(
            name='ReservationSeatSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10)),
                ('segment_no', models.IntegerField()),
                ('seat_no', models.CharField(blank=True, help_text='좌석 번호 (예: 12A)', max_length=10, null=True)),
                ('seat_note', models.TextField(blank=True, help_text='테스트 저장용 메모', null=True)),
            ],
            options={
                'db_table': 'reservation_seat_selections',
            },
        ),
    ]
