# Generated by Django 6.0 on 2025-12-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReservationFlight',
            fields=[
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flight_detail', serialize=False, to='reservations.reservation')),
                ('trip_type', models.CharField(choices=[('ONEWAY', 'One Way'), ('ROUNDTRIP', 'Round Trip')], max_length=10)),
                ('cabin_class', models.CharField(help_text='좌석 등급', max_length=30)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('baggage_info', models.TextField(blank=True, help_text='수하물 정보', null=True)),
                ('refund_rule', models.TextField(blank=True, help_text='환불/변경 규정', null=True)),
                ('special_request', models.TextField(blank=True, help_text='특별 요청사항', null=True)),
                ('contact_email', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'reservation_flights',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationflightsegment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationpassenger',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationseatselection',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='reservations.reservationpassenger'),
        ),
        migrations.AddField(
            model_name='reservationseatselection',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_selections', to='reservations.reservation'),
        ),
    ]
