# Generated by Django 6.0 on 2025-12-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='plans.travelplan'),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.travelplan'),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plans.travelpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.travelpost'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user'], name='travel_plan_user_id_b0bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['created_at'], name='travel_plan_created_5a109e_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['is_public'], name='travel_plan_is_publ_464b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user', 'is_public'], name='travel_plan_user_id_fb3ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['plan'], name='plan_detail_plan_id_7b4781_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['date'], name='plan_detail_date_ac2446_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['place'], name='plan_detail_place_i_020c45_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['user'], name='travel_post_user_id_4defaa_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['plan'], name='travel_post_plan_id_a38e67_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['created_at'], name='travel_post_created_d8ddb5_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['like_count'], name='travel_post_like_co_d07035_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['-like_count', '-created_at'], name='travel_post_like_co_3fc30b_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['destination'], name='travel_post_destina_39ee0a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['-view_count'], name='travel_post_view_co_c3e845_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user'], name='post_likes_user_id_7d46ab_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['created_at'], name='post_likes_created_c52989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='comments_parent__4366da_idx'),
        ),
    ]
