# Generated by Django 6.0 on 2025-12-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAKAO', 'Kakao API'), ('USER', 'User Registered')], default='KAKAO', max_length=50)),
                ('place_api_id', models.CharField(blank=True, help_text='카카오맵 장소 ID', max_length=50, null=True, unique=True)),
                ('name', models.TextField(help_text='장소 이름')),
                ('category_main', models.CharField(help_text='메인 카테고리 (예: 음식점, 관광지)', max_length=50)),
                ('category_detail', models.JSONField(blank=True, default=list, help_text='상세 카테고리 리스트')),
                ('address', models.TextField(help_text='도로명 주소')),
                ('city', models.CharField(db_index=True, help_text='도시 (필터링용)', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('thumbnail_urls', models.JSONField(blank=True, default=list, help_text='이미지 URL 리스트', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='PlaceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'place_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'place_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
