# Generated by Django 6.0 on 2025-12-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placebookmark',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='places.place'),
        ),
        migrations.AddField(
            model_name='placebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placereview',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='places_city_3bba99_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['provider'], name='places_provide_7560e6_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_api_id'], name='places_place_a_84b8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='placebookmark',
            index=models.Index(fields=['user'], name='place_bookm_user_id_8cc1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='placebookmark',
            index=models.Index(fields=['created_at'], name='place_bookm_created_5477d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placebookmark',
            unique_together={('user', 'place')},
        ),
    ]
